# Generated by Django 4.0.6 on 2022-08-27 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField(max_length=400)),
                ('output', models.TextField(max_length=400)),
            ],
        ),
    ]
