# Generated by Django 4.0.6 on 2022-08-27 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='output',
        ),
    ]
